server:
  port: 9002
  tomcat:
    maxThreads: 200
    maxConnections: 1000
    acceptCount: 500
    minSpareThreads: 200

# spring配置
spring:
  application:
    name: dataquery

# tsdb配置,此处说明同数据处理
aliyun:
  tsdb:
    host: ts-2ze583zll1242h95j.hitsdb.tsdb.aliyuncs.com
    port: 8242
    tsql:
      port: 3306
      host: ts-2ze583zll1242h95j.tsql.hitsdb.rds.aliyuncs.com
    # 原始数据时间线,必须与数据处理中一致
    original: airOriginal_v2
    # 移动平均值时间线,必须与数据处理中一致
    airdata: airData_v2
