# ----------------------------------------
# SERVER 端口等配置
# ----------------------------------------
server:
  port: 9001
  tomcat:
    maxThreads: 200
    maxConnections: 1000
    acceptCount: 500
    minSpareThreads: 200

# ----------------------------------------
# Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
# ----------------------------------------
spring:
  application:
    name: datacleaning
  redis:
    database: 0
    host: r-2zepdomycsuw74epdm.redis.rds.aliyuncs.com
    port: 6379
    password: AirRedis@666
    timeout: 200
    pool:
      maxTotal: 2000

# ----------------------------------------
# REDIS KEYS
# ----------------------------------------
air:
  data:
    avg: zhiyuan_database_air:data1:avg
    record: zhiyuan_database_air:data1:record
    ravg: zhiyuan_database_air:data1:repair_avg
    rrecord: zhiyuan_database_air:data1:repair_record
    device-tags: zhiyuan_database_air:devices:tags
    device-timestamp: zhiyuan_database_air:devices:timestamp
    device-update: zhiyuan_database_air:updata:devices
    prothreshold: zhiyuan_database_air:prothreshold:tags
    prostatusstage: zhiyuan_database_air:prostatusstage:tags
# iot.client必须与硬件连接服务里面iot.client一致
iot:
  client: zhiyuan_database_iot:auth:client

# ----------------------------------------
# TSDB PROPERTIES
# ----------------------------------------
aliyun:
  tsdb:
    # 这里需要设置阿里云控制台里面的地址，注意tsql与tsdb地址不同
    host: ts-2ze583zll1242h95j.hitsdb.tsdb.aliyuncs.com
    port: 8242
    tsql:
      port: 3306
      host: ts-wz9q4b40u613itu9c.tsql.hitsdb.rds.aliyuncs.com
    # 原始数据时间线
    original: airOriginal_v2
    # 移动平均值时间线
    airdata: airData_v2

# ----------------------------------------
# KAFKA PROPERTIES
# ----------------------------------------
kafka:
  topic-name: device-report
  topic-message-name: device-message
  consumer:
    servers: 192.168.0.201:9092,192.168.0.200:9092,192.168.0.199:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 10000
    auto:
      commit:
        interval: 5000
      offset:
        reset: earliest
    group:
      id: device-report
    concurrency: 1

  producer:
    servers: 192.168.0.201:9092,192.168.0.200:9092,192.168.0.199:9092
    retries: 0
    compression:
      type: snappy
    batch:
      size: 16384
    linger: 5
    buffer:
      memory: 33554432

# ----------------------------------------
# 移动平均值和故障值快照存储位置
# ----------------------------------------
file:
  average: /data/yingjian/
  break-down: /data/yingjianbreakdown/